services:
  - type: web
    name: lunqo-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: DOMAIN
        value: https://lunqo-app.onrender.com
      - key: ALLOWED_ORIGINS
        value: https://lunqo-app.onrender.com 